---
- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    pg_version_to_install: "{{ lookup('env', 'VERSION') | replace('ppg-','') }}"

- name: End play on RedHat 10 and 17.5 and older versions
  fail:
    msg: "Stopping execution on rhel 10 because 17.5 and below are not supported."
  when: ansible_os_family == "RedHat" and
   ansible_distribution_major_version == "10" and
   pg_version_to_install | string is version('17.5', '<=', strict=True)

#Uncomment once Debain-13 is integrated and stable on 17.6 using testing repo
# - name: End play on Debian 13 and 17.6 and older versions
#   fail:
#     msg: "Stopping execution on Debian 13 because 17.6 and below are not supported."
#   when: ansible_os_family == "Debian" and
#    ansible_distribution_major_version == "13" and
#    pg_version_to_install | string is version('17.6', '<=', strict=True)

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install Percona Platform for PostgreSQL 17 packages
  include_tasks: ../../../../tasks/install_ppg17.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-17/bin/postgresql-17-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-17
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg17_tools.yml

# # =========Telemetry testcases
# - name: Verify telemetry installation
#   include_tasks: ../../../../tasks/verify_telemetry.yml

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir

- name: Delete dpkg-query for RHEL
  yum:
    name: dpkg
    state: absent
  when: ansible_os_family == "RedHat"
