---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql18
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql-server-dev-all
          - percona-postgresql18
          - percona-postgresql18-contrib
          - percona-postgresql18-debuginfo
          - percona-postgresql18-devel
          - percona-postgresql18-docs
          - percona-postgresql18-libs
          - percona-postgresql18-llvmjit
          - percona-postgresql18-plperl
          - percona-postgresql18-plpython
          - percona-postgresql18-pltcl
          - percona-postgresql18-server
          - percona-postgresql18-test
          - percona-postgresql18-debuginfo
          - percona-postgresql18-debugsource
          - percona-postgresql18-devel-debuginfo
          - percona-postgresql18-libs-debuginfo
          - percona-postgresql18-plperl-debuginfo
          - percona-postgresql18-plpython3-debuginfo
          - percona-postgresql18-pltcl-debuginfo
          - percona-postgresql18-server-debuginfo
          - percona-pgbadger
          - percona-pgbouncer
          - percona-pgaudit18_set_user
          - percona-wal2json18
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit rpm packages
      yum:
        name: percona-pgaudit
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack18
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pgbackrest rpm packages
      yum:
        name: percona-pgbackrest
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni rpm packages
      yum:
        name: percona-patroni
        state: absent
      when: ansible_os_family == "RedHat"
